/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pkg1stquarter;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author MICHAE LOU LIM
 */
public class MainFrame extends javax.swing.JFrame {

    public static MainFrame instance;

    static void AddRowToJTable(String selectedName) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jtexttotal = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        cleartotal = new javax.swing.JButton();
        Payment = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        Paybtn = new javax.swing.JButton();
        Changetxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        backbutton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NAME", "PRICE"
            }
        ));
        jTable1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jTable1AncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 257, 169));

        jtexttotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtexttotalActionPerformed(evt);
            }
        });
        getContentPane().add(jtexttotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, 100, 30));

        jLabel1.setText("TOTAL :");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, 50, 30));

        jButton2.setText("CALCULATE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 110, 40));

        cleartotal.setText("Clear");
        cleartotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cleartotalActionPerformed(evt);
            }
        });
        getContentPane().add(cleartotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 190, -1, -1));

        Payment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PaymentActionPerformed(evt);
            }
        });
        getContentPane().add(Payment, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 230, 100, 30));

        jLabel2.setText("PAYMENT:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, -1, -1));

        Paybtn.setText("Pay");
        Paybtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PaybtnActionPerformed(evt);
            }
        });
        getContentPane().add(Paybtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 230, -1, -1));

        Changetxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChangetxtActionPerformed(evt);
            }
        });
        getContentPane().add(Changetxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 270, 100, 30));

        jLabel3.setText("CHANGE:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 280, -1, -1));

        backbutton.setText("RETURN TO STORE");
        backbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(backbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 310, 160, 30));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NAME ", "PRICE", "QUANTITY", "TOTAL"
            }
        ));
        jTable2.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jTable2AncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane2.setViewportView(jTable2);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 20, 290, 230));

        jButton1.setText("SALES");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 260, 150, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtexttotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtexttotalActionPerformed
        jtexttotal.setText(String.format("%.2f", jtexttotal));
    }//GEN-LAST:event_jtexttotalActionPerformed
    public static MainFrame getInstance() {
        if (instance == null) {
            instance = new MainFrame();
        }
        return instance;
    }
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        double total = 0;
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

        for (int i = 0; i < model.getRowCount(); i++) {
            try {
                double price = Double.parseDouble(model.getValueAt(i, 2).toString());
                total += price;
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Invalid price value in row " + (i + 1));
                return;
            }
        }

        // Display total directly in the jTextFieldTotal
        jtexttotal.setText(String.format("%.2f", +total));
    }//GEN-LAST:event_jButton2ActionPerformed

    private void cleartotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cleartotalActionPerformed
        jtexttotal.setText("");
        Payment.setText("");
        Changetxt.setText("");
        
    }//GEN-LAST:event_cleartotalActionPerformed

    private void PaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PaymentActionPerformed
        
    }//GEN-LAST:event_PaymentActionPerformed

    private void PaybtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PaybtnActionPerformed

        String totalText = jtexttotal.getText();
        String paymentText = Payment.getText();

// Convert to double
        double total = Double.parseDouble(totalText);
        double payment = Double.parseDouble(paymentText);

// Do the math
        double pay = payment - total;

// Convert the double result to String
        String payText = String.valueOf(pay);

// Set the result into the text field
        Changetxt.setText(payText);


    }//GEN-LAST:event_PaybtnActionPerformed

    private void ChangetxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChangetxtActionPerformed

    }//GEN-LAST:event_ChangetxtActionPerformed

    private void backbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbuttonActionPerformed
        dispose();


    }//GEN-LAST:event_backbuttonActionPerformed

    private void jTable1AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jTable1AncestorAdded


    }//GEN-LAST:event_jTable1AncestorAdded

    private void jTable2AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jTable2AncestorAdded
       
    }//GEN-LAST:event_jTable2AncestorAdded

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jButton1.getText();
        
    }//GEN-LAST:event_jButton1ActionPerformed
    public static void AddRowToJTable(Object[] dataRow) {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(dataRow);
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Changetxt;
    private javax.swing.JButton Paybtn;
    private javax.swing.JTextField Payment;
    private javax.swing.JButton backbutton;
    private javax.swing.JButton cleartotal;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private static javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jtexttotal;
    // End of variables declaration//GEN-END:variables

    void addRowToTable(String selectedName) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
